### ISSUE TITLE
How to set Ingenico setting under "Global security parameters"?

### ISSUE THREAD

**Issue by postback** [maciejzgadzaj/commerce_ingenico#5]
Hi,

In configuring a test-account at Ingenico, under "Global security parameters", there's indeed 2 settings:
- Hash algorithm
- Character encoding

But on a production account, I get to choose another, third setting:
Compose the string to be hashed by concatenating the value of
With possible values:
- Main parameters only.
- Each parameter followed by the passphrase. (Please refer to our integration guides for further details)

What to select for this setting? The docs don't seem to mention that setting.

Thanks.

**Comment by maciejzgadzaj** [comment]
From what I remember it's probably "Each parameter followed by the passphrase" - but then again, haven't used the module and done any new dev for quite some time now. Just give both a try and see which one works?

**Comment by postback** [comment]
For posterity: selecting "Each parameter followed by the passphrase. (Please refer to our integration guides for further details)" works.
